version: '3'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - data:/data
volumes:
  data:
networks:
  default:
    external:
      name: docker-network
