version: '3'
services:
  wordpress:
    image: wordpress
    container_name: wordpress
    ports:
      - '8080:80'
    environment:
      WORDPRESS_DB_PASSWORD: password
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - data:/var/lib/mysql
    command: [
      "--log-bin=mysql-bin",
      "--server-id=1"
    ]
volumes:
  data:
networks:
  default:
    external:
      name: docker-network
