server:
  port: 8765
spring:
  application:
    name: eurekaclient
  rabbitmq:
    host: 39.96.69.79
    port: 5672
    username: rabbitmq
    password: rabbitmq
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability : 1    